hash-format = "sha256"

[[files]]
file = "mods/autoreconnect.pw.toml"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
metafile = true

[[files]]
file = "mods/better-fps-render-distance-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config-legacy.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
metafile = true

[[files]]
file = "mods/detail-armor-bar.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forgetmechunk.pw.toml"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
metafile = true

[[files]]
file = "mods/kronhud.pw.toml"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/logical-zoom.pw.toml"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
metafile = true

[[files]]
file = "mods/microdurability.pw.toml"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/name-pain.pw.toml"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-crashes.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-scrolling-everywhere-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
metafile = true

[[files]]
file = "mods/ugly-scoreboard-fix.pw.toml"
metafile = true

[[files]]
file = "mods/visible-barriers.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true
