name = "Optimize"
author = "BetaTester41"
version = "1.18.x"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f091ecd05a811dd5713500e1a01a28bc7dfef1992839f8863ab17a77387348a"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.7"

[options]
acceptable-game-versions = ["1.18.1"]
no-internal-hashes = "true"
