name = "Optimize"
author = "BetaTester41"
version = "1.18.x"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f0cdba3cf4a9509848024d573af2fefeef8e5847eaad2ad0d5646ff28685568"

[versions]
fabric = "0.12.12"
minecraft = "1.18"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
no-internal-hashes = "true"
