name = "Optimize"
author = "BetaTester41"
version = "1.18.X"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79d6e1bf5bc220e8d209423cdf995727d77995df3335df309acc8d9b67c9939b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
no-internal-hashes = "true"
