name = "Optimize"
author = "BetaTester41"
version = "1.18.x"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c65c5e34393fb818f78913289fcce536a74be0d445e347adaef6a58454bea0c"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
