name = "Optimize"
author = "BetaTester41"
version = "1.18.x"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08b52f3ee9b32fd3aa93b687a5f84c7818e929a26e88450988b350a491bcf75c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.7"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
no-internal-hashes = "true"
